fix: margin on select component
brunocroh/bolhadev.chat pull request #11
Opened 2024-05-31 00:00 UTC by birobirobiro

Before:

![image](https://github.com/brunocroh/bolhadev.chat/assets/22185823/3ededb28-0e4d-41df-b282-c61e866fe4cc)

After:

![image](https://github.com/brunocroh/bolhadev.chat/assets/22185823/8a7ba556-78b6-4ba4-9155-a449056b8f3b)

2024-06-02 10:44 UTC, brunocroh requested changes
Firstly, I really appreciate your contribution, so thank you for it.

I just need you to reset the changes to `.env.template` and `pnpm-lock.yaml` so I can merge them.

2024-06-02 10:44 UTC, brunocroh commented on .env.template
This file cannot be deleted.

2024-06-02 10:44 UTC, brunocroh commented on pnpm-lock.yaml
Reset this change on pnpm-lock.yaml

2024-06-02 10:44 UTC, brunocroh commented on apps/web/components/video-player.tsx
We updated the prettier and add more features to this component, so could you please solve this conflicts to me be able to merge it?

2024-06-03 16:47 UTC, birobirobiro commented on apps/web/components/video-player.tsx
Sure! I'll resolve the conflicts and push the updates tonight.

2024-06-03 16:49 UTC, closed without merging